<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\User;
use App\Models\Api\TBusinessOwnerInfo;
use App\Models\Api\TBusiness;
use App\Models\Api\TOperationHour;
use App\Models\Api\TBusinessGallery;
use Illuminate\Support\Facades\Hash;

class TBusinessOwnerSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $tUser = User::insert([
            [
                'first_name' => 'Azam',
                'last_name' => 'Hassim', 
                'name' => 'Azam Hassim',
                'email' => 'azam.hh@gmail.com',
                'password' =>  Hash::make('12345678'), 
                'account_type' => 'GB',
            ],
            [
                'first_name' => 'Surah',
                'last_name' => 'Hassim', 
                'name' => 'Surah Hassim',
                'email' => 'azam1.hh@gmail.com',
                'password' => Hash::make('12345678'), 
                'account_type' => 'GB',
            ],
            [
                'first_name' => 'Mikaeel',
                'last_name' => 'Hassim', 
                'name' => 'Mikaeel Hassim',
                'email' => 'Mikaeel@gmail.com',
                'password' => Hash::make('12345678'), 
                'account_type' => 'GB',
            ],
            [
                'first_name' => 'Sana',
                'last_name' => 'Shaikh',
                'name' => 'Sana Shaikh',
                'email' => 'Sana@gmail.com',
                'password' => Hash::make('12345678'), 
                'account_type' => 'GB',
            ],
            [
                'first_name' => 'Azam',
                'last_name' => 'Hassim',
                'name' => 'Azam Hassim',
                'email' => 'azam2.hh@gmail.com',
                'password' => Hash::make('12345678'),  
                'account_type' => 'GB',
            ],
            [
                'first_name' => 'Hal',
                'last_name' => 'Al',
                'name' => 'Azam Hassim',
                'email' => 'Hal@gmail.com',
                'password' => Hash::make('12345678'), 
                'account_type' => 'GB',
            ],
            [
                'first_name' => 'Mr.',
                'last_name' => 'Nazim',
                'name' => 'Mr. Nazim',
                'email' => 'nazim11121@gamil.com',
                'password' => Hash::make('12345678'), 
                'account_type' => 'GB',
            ],
        ]);
        $tBusinessOwnerInfo = TBusinessOwnerInfo::insert([
            [
                'user_id' => 1,
                'first_name' => 'Azam',
                'last_name' => 'Hassim', 
                'email' => 'azam.hh@gmail.com', 
                'phone_number' => '4086930134', 
                'address' => '21329 Gosier Way',
            ],
            [
                'user_id' => 2,
                'first_name' => 'Surah',
                'last_name' => 'Hassim', 
                'email' => 'azam.hh@gmail.com', 
                'phone_number' => '1234567890', 
                'address' => '20423 US-441 Suite F18', 
            ],
            [
                'user_id' => 3,
                'first_name' => 'Mikaeel',
                'last_name' => 'Hassim', 
                'email' => 'Mikaeel@gmail.com', 
                'phone_number' => '2345678901', 
                'address' => '8185 Via Ancho Rd',
            ],
            [
                'user_id' => 4,
                'first_name' => 'Sana',
                'last_name' => 'Shaikh', 
                'email' => 'Sana@gmail.com', 
                'phone_number' => '4444444444', 
                'address' => '2005 Greenbriar Blvd',
            ],
            [
                'user_id' => 5,
                'first_name' => 'Azam',
                'last_name' => 'Hassim', 
                'email' => 'azam.hh@gmail.com', 
                'phone_number' => '5557890345', 
                'address' => '19196 Natures View Ct',
            ],
            [
                'user_id' => 6,
                'first_name' => 'Hal',
                'last_name' => 'Al', 
                'email' => 'Hal@gmail.com', 
                'phone_number' => '8888888888', 
                'address' => '7501 Harwin Dr. #101e',
            ],
            [
                'user_id' => 7,
                'first_name' => 'Mr.',
                'last_name' => 'Nazim', 
                'email' => 'nazim11121@gamil.com',
                'phone_number' => '01778213921', 
                'address' => 'Level 1, House 1A, Road No. 16/A, Gulshan 1, Dhaka 1212',
            ],
        ]);
        $tBusiness = TBusiness::insert([
            [
                'business_owner_id' => 1,
                'business_name' => 'Five Pillars Ventures LLC',
                'business_type_id' => json_encode(['1']), 
                'business_category_id' => '1', 
                'creed_tags_id' => json_encode(['1','2','3']), 
                'restaurant_id' => '',
                'business_email' => 'azam.hh@gmail.com',
                'business_phone_number' => '4086930134',
                'customer_hotline' => '4086930134',
                'customer_email_leads' => 'azam.hh@gmail.com',
                'address' => '21329 Gosier Way',
                'lat' => '26.3562011',
                'long' => '-80.2474052',
                'country' => '233',
                'state' => '1436',
                'city' => '112494',
                'zip_code' => '33428',
                'description' => 'app development information technology consulting',
            ],
            [
                'business_owner_id' => 2,
                'business_name' => 'Muslim Dentist LLC',
                'business_type_id' => json_encode(['2']), 
                'business_category_id' => 2, 
                'creed_tags_id' => json_encode(['1','2','3']), 
                'restaurant_id' => '',
                'business_email' => 'MuslimDentistLLC@gmail.com',
                'business_phone_number' => '1234567890',
                'customer_hotline' => '1234567890',
                'customer_email_leads' => 'MuslimDentistLLC@gmail.com',
                'address' => '20423 US-441 Suite F18',
                'lat' => '26.3767221',
                'long' => '-80.2065753',
                'country' => '233',
                'state' => '1436',
                'city' => '112494',
                'zip_code' => '33498', 
                'description' => 'Dental Surgeon Dentist Dental Hygeine',
            ],
            [
                'business_owner_id' => 3,
                'business_name' => 'Muslim Law LLC',
                'business_type_id' => json_encode(['3']), 
                'business_category_id' => 3, 
                'creed_tags_id' => json_encode(['1','2','3']), 
                'restaurant_id' => '',
                'business_email' => 'Mikaeel@gmail.com',
                'business_phone_number' => ' 3333333333',
                'customer_hotline' => ' 3333333333',
                'customer_email_leads' => 'Mikaeel@gmail.com',
                'address' => '8185 Via Ancho Rd',
                'lat' => '26.3612422',
                'long' => '-80.1785146',
                'country' => '233',
                'state' => '1436',
                'city' => '112494',
                'zip_code' => '33488', 
                'description' => 'Lawyer Family Law Probate Custody Divorce',
            ],
            [
                'business_owner_id' => 4,
                'business_name' => 'Lunar Events LLC',
                'business_type_id' => json_encode(['4']), 
                'business_category_id' => 4, 
                'creed_tags_id' => json_encode(['1','2','3']), 
                'restaurant_id' => '',
                'business_email' => 'Sana@gmail.com',
                'business_phone_number' => ' 5555555555',
                'customer_hotline' => ' 5555555555',
                'customer_email_leads' => 'Sana@gmail.com',
                'address' => '2005 Greenbriar Blvd',
                'lat' => '26.6456944',
                'long' => '-80.2919912',
                'country' => '233',
                'state' => '1436',
                'city' => '128776',
                'zip_code' => '33414',
                'description' => 'event planning parties corporate events birthday planner wedding fun outdoor florida event planner',
            ],
            [
                'business_owner_id' => 5,
                'business_name' => 'Halal Food Restaurant LLC',
                'business_type_id' => json_encode(['5']), 
                'business_category_id' => 5, 
                'creed_tags_id' => json_encode(['1','2','3']), 
                'restaurant_id' => json_encode(['1']),
                'business_email' => 'restaurantLLC@gmail.com',
                'business_phone_number' => ' 9999999999',
                'customer_hotline' => ' 9999999999',
                'customer_email_leads' => 'restaurantLLC@gmail.com',
                'address' => '19196 Natures View Ct',
                'lat' => '26.3898274',
                'long' => '-80.236841',
                'country' => '233',
                'state' => '1436',
                'city' => '112494',
                'zip_code' => '33498',
                'description' => 'halal yemeni arab restaurant',
            ],
            [
                'business_owner_id' => 6,
                'business_name' => 'Italian Restaurant LLC',
                'business_type_id' => json_encode(['6']), 
                'business_category_id' => 5, 
                'creed_tags_id' => json_encode(['3']), 
                'restaurant_id' => json_encode(['2']),
                'business_email' => '',
                'business_phone_number' => ' ',
                'customer_hotline' => ' ',
                'customer_email_leads' => '',
                'address' => '7501 Harwin Dr. #101e',
                'lat' => '29.7163364',
                'long' => '-95.5196025',
                'country' => '233',
                'state' => '1407',
                'city' => '118703',
                'zip_code' => '77036',  
                'description' => 'Halal Italian Restaurant pizza pasta',
            ],
            [
                'business_owner_id' => 7,
                'business_name' => 'Analyzen2.0',
                'business_type_id' => json_encode(['1']), 
                'business_category_id' => '1', 
                'creed_tags_id' => json_encode(['1','2','3']), 
                'restaurant_id' => '',
                'business_email' => 'nazim@analyzenbd.com',
                'business_phone_number' => '01778213921',
                'customer_hotline' => '01778213921',
                'customer_email_leads' => 'nazim11121@gamil.com',
                'address' => 'Level 1, House 1A, Road No. 16/A, Gulshan 1, Dhaka 1212',
                'lat' => '23.7812753',
                'long' => '90.4101866',
                'country' => '19',
                'state' => '760',
                'city' => '153863',
                'zip_code' => '1212',
                'description' => 'web & app development information technology consulting',
            ],
        ]);
    }
}
